name: Build Android AAB

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Decode keystore
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/flowtracker-release-key.keystore

    - name: Create gradle.properties
      run: |
        cat >> android/gradle.properties << EOF
        
        # Signing configuration for release builds
        MYAPP_RELEASE_STORE_FILE=flowtracker-release-key.keystore
        MYAPP_RELEASE_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}
        MYAPP_RELEASE_STORE_PASSWORD=${{ secrets.ANDROID_STORE_PASSWORD }}
        MYAPP_RELEASE_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}
        EOF

    - name: Accept Android licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build Android App Bundle
      run: |
        cd android
        ./gradlew bundleRelease

    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: flowtracker-release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
        retention-days: 30

    - name: Upload mapping file
      uses: actions/upload-artifact@v4
      with:
        name: flowtracker-mapping
        path: android/app/build/outputs/mapping/release/mapping.txt
        retention-days: 30