name: Build iOS IPA

on:
  workflow_dispatch:
  # Temporarily disabled - focus on Android build
  # push:
  #   branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'
          
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
          
      - name: Sync Capacitor
        run: npx cap sync ios
        
      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          
      - name: Build iOS Archive
        run: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath App.xcarchive \
                     archive
                     
      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
                     -archivePath App.xcarchive \
                     -exportPath . \
                     -exportOptionsPlist ExportOptions.plist
                     
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: ios/App.ipa
          retention-days: 30