name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'
          
      - name: Setup Java Latest (Required for Capacitor)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 'latest'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        
      - name: Install Android SDK components
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"
        
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
          
      - name: Sync Capacitor (Critical Step)
        run: |
          echo "Using Node $(node -v) at $(command -v node)"
          echo "process.version test:"
          node -e "console.log('process.version:', process.version)"
          echo "version comparison:"
          node -e "console.log('node --version equivalent:', process.version); console.log('version check >=20.0.0:', parseInt(process.version.slice(1)) >= 20)"
          echo "Using local Capacitor CLI at $(node -p "require.resolve('@capacitor/cli/package.json')")"
          export PATH="$(dirname $(command -v node)):$PATH"
          echo "PATH: $PATH"
          node node_modules/.bin/cap sync android
        
      - name: Decode keystore (if available)
        working-directory: android
        run: |
          if [ -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
            echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.jks
            echo "Keystore decoded successfully"
          else
            echo "No keystore found - will build unsigned AAB"
          fi
        
      - name: Grant execute permission for gradlew
        working-directory: android
        run: chmod +x ./gradlew
        
      - name: Build Release AAB
        working-directory: android
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          if [ -f "my-release-key.jks" ]; then
            echo "Building signed AAB..."
            ./gradlew bundleRelease --no-configuration-cache -x lint -x test --stacktrace
          else
            echo "Building unsigned AAB (no keystore found)..."
            ./gradlew bundleRelease --no-configuration-cache -x lint -x test --stacktrace
          fi
        
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 30