name: 🍎 iOS App Store Build Pipeline

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'archive'
        type: choice
        options:
        - archive
        - simulator

jobs:
  ios-build:
    name: 🍎 Build iOS for App Store
    runs-on: macos-latest
    
    steps:
    - name: 📦 Checkout Repository
      uses: actions/checkout@v4
      
    - name: 🔧 Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: 📱 Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: 🔐 Setup Ruby and CocoaPods
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        
    - name: 💿 Install Node Dependencies
      run: |
        npm ci
        
    - name: 🏗️ Build Web Assets
      run: |
        npm run build
        
    - name: 🔄 Sync iOS Capacitor
      run: |
        npx cap sync ios
        
    - name: 💎 Install CocoaPods Dependencies
      run: |
        cd ios/App
        pod install --repo-update
        
    - name: 📱 Build iOS Archive (App Store)
      if: ${{ github.event.inputs.build_type == 'archive' }}
      run: |
        cd ios/App
        
        # Create archive for App Store
        xcodebuild archive \
          -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath build/FlowTracker.xcarchive \
          MARKETING_VERSION=1.0.0 \
          CURRENT_PROJECT_VERSION=1 \
          PRODUCT_BUNDLE_IDENTIFIER=xyz.flowtracker.app \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: 📦 Export IPA for App Store
      if: ${{ github.event.inputs.build_type == 'archive' }}
      run: |
        cd ios/App
        
        # Export archive to IPA
        xcodebuild -exportArchive \
          -archivePath build/FlowTracker.xcarchive \
          -exportPath build/export \
          -exportOptionsPlist ../../ExportOptions.plist \
          -allowProvisioningUpdates
          
    - name: 🔍 Verify Build Output
      run: |
        echo "=== iOS Build Verification ==="
        find ios/App/build -name "*.xcarchive" -o -name "*.ipa" | head -10
        
        if [ -f ios/App/build/export/FlowTracker.ipa ]; then
          echo "✅ IPA file generated successfully!"
          ls -lh ios/App/build/export/FlowTracker.ipa
        else
          echo "❌ IPA file not found"
          find ios/App/build -type f | head -20
        fi
        
    - name: 📤 Upload iOS Archive
      if: ${{ github.event.inputs.build_type == 'archive' }}
      uses: actions/upload-artifact@v4
      with:
        name: flowtracker-ios-archive
        path: |
          ios/App/build/FlowTracker.xcarchive
          ios/App/build/export/FlowTracker.ipa
        retention-days: 30
        
    - name: 📤 Upload Build Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-logs
        path: |
          ios/App/build/logs
          ~/Library/Developer/Xcode/DerivedData/**/Logs/**
        retention-days: 7
        if-no-files-found: ignore

    - name: 📊 Build Summary
      if: always()
      run: |
        echo "=== 🍎 iOS Build Summary ==="
        echo "Build Type: ${{ github.event.inputs.build_type }}"
        echo "Xcode Version: $(xcodebuild -version)"
        echo "iOS Simulators Available:"
        xcrun simctl list devices | grep -E "(iPhone|iPad)" | head -5
        
        if [ -f ios/App/build/export/FlowTracker.ipa ]; then
          echo "✅ FlowTracker IPA ready for App Store submission!"
          echo "File size: $(ls -lh ios/App/build/export/FlowTracker.ipa | awk '{print $5}')"
        fi