name: 🚀 PURE ANDROID BUILD (No Capacitor CLI)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js for web build only
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Setup Java for Android
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        
      - name: Install Android SDK components
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;34.0.0"
        
      - name: Build web assets ONLY (NO Capacitor)
        run: |
          echo "=== BUILDING WEB ASSETS ==="
          npm ci
          npm run build
          echo "Web build completed"
          ls -la dist/ || ls -la build/ || echo "No dist/build folder"
          
      - name: Copy web assets directly to Android (NO Capacitor CLI)
        run: |
          echo "=== COPYING WEB ASSETS TO ANDROID ==="
          
          # Clean and create Android assets directory
          rm -rf android/app/src/main/assets/public
          mkdir -p android/app/src/main/assets/public
          
          # Copy web assets (try both common locations)
          if [ -d "dist" ]; then
            echo "Copying from dist/ folder..."
            cp -r dist/* android/app/src/main/assets/public/
          elif [ -d "build" ]; then
            echo "Copying from build/ folder..."
            cp -r build/* android/app/src/main/assets/public/
          else
            echo "Creating minimal index.html..."
            echo "<!DOCTYPE html>" > android/app/src/main/assets/public/index.html
            echo "<html><head><title>FlowTracker</title></head>" >> android/app/src/main/assets/public/index.html
            echo "<body><div id=\"root\"><h1>FlowTracker</h1><p>Loading...</p></div></body></html>" >> android/app/src/main/assets/public/index.html
          fi
          
          echo "Assets copied successfully:"
          ls -la android/app/src/main/assets/public/
          
      - name: Verify Android project structure AND Capacitor dependencies
        run: |
          echo "=== ANDROID PROJECT VERIFICATION ==="
          echo "Checking for gradlew..."
          ls -la android/gradlew || echo "gradlew not found"
          
          echo "Checking build.gradle files..."
          ls -la android/build.gradle || echo "root build.gradle not found"
          ls -la android/app/build.gradle || echo "app build.gradle not found"
          
          echo "Checking assets..."
          ls -la android/app/src/main/assets/public/ || echo "assets not found"
          
          echo "=== CAPACITOR DEPENDENCIES VERIFICATION ==="
          echo "Checking Capacitor node modules..."
          ls -la node_modules/@capacitor/ || echo "Capacitor modules not found"
          ls -la node_modules/@capacitor/android/ || echo "Capacitor Android module not found"
          ls -la node_modules/@capacitor/android/capacitor/ || echo "Capacitor core Android not found"
          ls -la node_modules/@capacitor/android/capacitor-cordova-android-plugins/ || echo "Capacitor cordova plugins not found"
          
          echo "Checking plugin modules..."
          ls -la node_modules/@capacitor-community/admob/android/ || echo "AdMob plugin Android not found"
          ls -la node_modules/@capacitor/local-notifications/android/ || echo "Local notifications plugin Android not found"
          ls -la node_modules/@revenuecat/purchases-capacitor/android/ || echo "RevenueCat plugin Android not found"
          
      - name: Decode keystore for signing (if available)
        working-directory: android
        run: |
          if [ -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
            echo "Decoding keystore for signed build..."
            echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.jks
            echo "Keystore decoded successfully"
          else
            echo "No keystore - will build unsigned AAB"
          fi
          
      - name: Make gradlew executable
        working-directory: android
        run: chmod +x ./gradlew
        
      - name: Test Gradle build (debug first)
        working-directory: android
        run: |
          echo "=== TESTING GRADLE BUILD ==="
          # Configure Gradle for CI environment
          export GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.workers.max=2"
          
          ./gradlew clean --no-daemon --no-parallel --stacktrace
          ./gradlew assembleDebug --no-daemon --no-parallel --stacktrace --info
          echo "Debug build completed"
          
      - name: Build Release AAB (FINAL STEP)
        working-directory: android
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.workers.max=2"
        run: |
          echo "=== BUILDING RELEASE AAB ==="
          if [ -f "my-release-key.jks" ]; then
            echo "Building SIGNED AAB with keystore..."
          else
            echo "Building UNSIGNED AAB (no keystore found)..."
          fi
          
          # Add comprehensive diagnostics before build
          echo "=== PRE-BUILD DIAGNOSTICS ==="
          ./gradlew :app:dependencies --configuration releaseRuntimeClasspath || true
          
          echo "=== ATTEMPTING BUNDLE BUILD ==="
          ./gradlew bundleRelease --no-daemon --no-parallel --no-configuration-cache -x lint -x test --stacktrace --info --debug
          
          echo "=== CHECKING OUTPUT ==="
          find . -name "*.aab" -type f
          ls -la app/build/outputs/bundle/release/ || echo "Release folder not found"
          
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: flowtracker-release-aab
          path: android/app/build/outputs/bundle/release/*.aab
          retention-days: 30